#!/bin/sh
touch /etc/config/autoreboot

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autoreboot[-1]
	add ucitrack autoreboot
	set ucitrack.@autoreboot[-1].exec='/etc/init.d/autoreboot restart'
	commit ucitrack
EOF

# remove LuCI cache
rm -f /tmp/luci*
exit 0
