# Copyright 2017 Dirk Brenken (dev@brenken.org)
# # This is free software, licensed under the Apache License, Version 2.0
#
include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for wifimac
LUCI_DEPENDS:=
LUCI_PKGARCH:=all

#include ../../luci.mk
include $(TOPDIR)/feeds/luci/luci.mk
#include $(TOPDIR)/package/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
